[2023-09-07T10:12:37.202+0900] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_loader.execute_sql_query __airflow_temporary_run_2023-09-06T08:36:58.687397+00:00__ [queued]>
[2023-09-07T10:12:37.204+0900] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_loader.execute_sql_query __airflow_temporary_run_2023-09-06T08:36:58.687397+00:00__ [queued]>
[2023-09-07T10:12:37.204+0900] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-07T10:12:37.209+0900] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): execute_sql_query> on 2023-01-01 00:00:00+00:00
[2023-09-07T10:12:37.210+0900] {standard_task_runner.py:57} INFO - Started process 15220 to run task
[2023-09-07T10:12:37.213+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_loader', 'execute_sql_query', '__airflow_temporary_run_2023-09-06T08:36:58.687397+00:00__', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/postgres_loader.py', '--cfg-path', '/var/folders/6z/txp71s3x4xdgbkrqmmm6vvrc0000gn/T/tmprw584ri0']
[2023-09-07T10:12:37.214+0900] {standard_task_runner.py:85} INFO - Job 20: Subtask execute_sql_query
[2023-09-07T10:12:37.234+0900] {task_command.py:415} INFO - Running <TaskInstance: postgres_loader.execute_sql_query __airflow_temporary_run_2023-09-06T08:36:58.687397+00:00__ [running]> on host sangwanui-macbookpro.local
[2023-09-07T10:12:37.259+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='postgres_loader' AIRFLOW_CTX_TASK_ID='execute_sql_query' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='__airflow_temporary_run_2023-09-06T08:36:58.687397+00:00__'
[2023-09-07T10:12:37.259+0900] {sql.py:274} INFO - Executing: 
        INSERT INTO sample_table (key, value)
        VALUES ('hello', 'world')
    
[2023-09-07T10:12:37.263+0900] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_postgres_connection` isn't defined
[2023-09-07T10:12:37.268+0900] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_loader, task_id=execute_sql_query, execution_date=20230101T000000, start_date=20230907T011237, end_date=20230907T011237
[2023-09-07T10:12:37.281+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task execute_sql_query (The conn_id `my_postgres_connection` isn't defined; 15220)
[2023-09-07T10:12:37.319+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-07T10:12:37.325+0900] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
