[2023-09-07T10:38:06.471+0900] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_loader.execute_sql_query __airflow_temporary_run_2023-09-07T01:38:05.641645+00:00__ [queued]>
[2023-09-07T10:38:06.474+0900] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_loader.execute_sql_query __airflow_temporary_run_2023-09-07T01:38:05.641645+00:00__ [queued]>
[2023-09-07T10:38:06.474+0900] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-07T10:38:06.479+0900] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): execute_sql_query> on 2023-01-02 00:00:00+00:00
[2023-09-07T10:38:06.481+0900] {standard_task_runner.py:57} INFO - Started process 17715 to run task
[2023-09-07T10:38:06.483+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_loader', 'execute_sql_query', '__airflow_temporary_run_2023-09-07T01:38:05.641645+00:00__', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/postgres_loader.py', '--cfg-path', '/var/folders/6z/txp71s3x4xdgbkrqmmm6vvrc0000gn/T/tmpx16tauco']
[2023-09-07T10:38:06.484+0900] {standard_task_runner.py:85} INFO - Job 47: Subtask execute_sql_query
[2023-09-07T10:38:06.501+0900] {task_command.py:415} INFO - Running <TaskInstance: postgres_loader.execute_sql_query __airflow_temporary_run_2023-09-07T01:38:05.641645+00:00__ [running]> on host sangwanui-macbookpro.local
[2023-09-07T10:38:06.693+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='postgres_loader' AIRFLOW_CTX_TASK_ID='execute_sql_query' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='__airflow_temporary_run_2023-09-07T01:38:05.641645+00:00__'
[2023-09-07T10:38:06.694+0900] {sql.py:274} INFO - Executing: 
        INSERT INTO sample_table (key, value)
        VALUES ('hello', 'world')
    
[2023-09-07T10:38:06.698+0900] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_postgres_connection` isn't defined
[2023-09-07T10:38:06.701+0900] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_loader, task_id=execute_sql_query, execution_date=20230102T000000, start_date=20230907T013806, end_date=20230907T013806
[2023-09-07T10:38:06.704+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 47 for task execute_sql_query (The conn_id `my_postgres_connection` isn't defined; 17715)
[2023-09-07T10:38:06.723+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-07T10:38:06.729+0900] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
