[2023-09-07T10:19:21.002+0900] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_loader.execute_sql_query manual__2023-09-07T01:19:19.292931+00:00 [queued]>
[2023-09-07T10:19:21.005+0900] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_loader.execute_sql_query manual__2023-09-07T01:19:19.292931+00:00 [queued]>
[2023-09-07T10:19:21.005+0900] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-07T10:19:21.009+0900] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): execute_sql_query> on 2023-09-07 01:19:19.292931+00:00
[2023-09-07T10:19:21.010+0900] {standard_task_runner.py:57} INFO - Started process 15795 to run task
[2023-09-07T10:19:21.013+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_loader', 'execute_sql_query', 'manual__2023-09-07T01:19:19.292931+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/postgres_loader.py', '--cfg-path', '/var/folders/6z/txp71s3x4xdgbkrqmmm6vvrc0000gn/T/tmpemckma9o']
[2023-09-07T10:19:21.014+0900] {standard_task_runner.py:85} INFO - Job 26: Subtask execute_sql_query
[2023-09-07T10:19:21.027+0900] {task_command.py:415} INFO - Running <TaskInstance: postgres_loader.execute_sql_query manual__2023-09-07T01:19:19.292931+00:00 [running]> on host sangwanui-macbookpro.local
[2023-09-07T10:19:21.170+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='postgres_loader' AIRFLOW_CTX_TASK_ID='execute_sql_query' AIRFLOW_CTX_EXECUTION_DATE='2023-09-07T01:19:19.292931+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-07T01:19:19.292931+00:00'
[2023-09-07T10:19:21.170+0900] {sql.py:274} INFO - Executing: 
        INSERT INTO sample_table (key, value)
        VALUES ('hello', 'world')
    
[2023-09-07T10:19:21.173+0900] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/Users/sangwanlee/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_postgres_connection` isn't defined
[2023-09-07T10:19:21.176+0900] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_loader, task_id=execute_sql_query, execution_date=20230907T011919, start_date=20230907T011921, end_date=20230907T011921
[2023-09-07T10:19:21.178+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task execute_sql_query (The conn_id `my_postgres_connection` isn't defined; 15795)
[2023-09-07T10:19:21.209+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-07T10:19:21.215+0900] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
